### PR TITLE
TCOTA-493 TCOTA-553 duplicate treatment when duplicating assignments

### PR DESCRIPTION
**Pull request by relong76**

### CODE REVIEW

**Review by machristie — APPROVED** [review]
LGTM 👍

**Comment by machristie** [comment]
@relong76 can you resolve the merge conflicts?

**Comment by relong76** [comment]
@machristie conflicts fixed!

**Comment by machristie** [comment]
Oh no, I just merged #330 and now it looks like there are merge conflicts again. Hopefully they're not too bad. @relong76

**Pull request merged**
